---

- name: Assert task variables are defined
  ansible.builtin.assert:
      that:
      - project_name is defined

- name: Assert variables are defined for project create
  ansible.builtin.assert:
      that:
      - merge_method is defined
      - merge_method in ["merge", "rebase_merge", "ff"]
      - visibility is defined
      - visibility in ["private", "internal", "public"]
  when: action == "project_create"

- name: Create Gitlab project
  ansible.builtin.uri:
    url: "{{ gitlab_projects_url }}"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: "{{ lookup('ansible.builtin.template','prj_cu_req.json.j2') }}"
    body_format: json
    return_content: yes
    status_code: 201
    timeout: 3
  register: _gitlab_response
  retries: 3
  delay: 5
  until: _gitlab_response.status == 201
  changed_when: _gitlab_response.status == 201
  when: 
    - action == "project_create"


- ansible.builtin.include_tasks: gitlabprjlist_get.yml
  when: action in ["project_update", "project_delete"]

- name: Lookup existing Gitlab project
  ansible.builtin.set_fact:
    projects_found_by_name: "{{ gitlab_projects_list | selectattr('name', 'equalto', project_name) | list }}"
  when: action in ["project_update", "project_delete"]

- name: Fail if zero or more than one project found
  ansible.builtin.fail:
    msg: "{{ projects_found_by_name | length }} projects found with name {{ project_name }}"
  when: 
    - action in ["project_update", "project_delete"]
    - projects_found_by_name | length != 1

- name: Extract project id
  ansible.builtin.set_fact:
    project_id: "{{ projects_found_by_name[0].id }}"
  when: 
    - action in ["project_update", "project_delete"]

- name: Update Gitlab project
  ansible.builtin.uri:
    url: "{{ gitlab_projects_url }}/{{ project_id }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: "{{ lookup('ansible.builtin.template','prj_cu_req.json.j2') }}"
    body_format: json
    return_content: yes
    status_code: 200
    timeout: 3
  register: _gitlab_response
  retries: 3
  delay: 5
  until: _gitlab_response.status == 200
  changed_when: _gitlab_response.status == 200
  when: action == "project_update"

- name: Delete Gitlab project
  ansible.builtin.uri:
    url: "{{ gitlab_projects_url }}/{{ project_id }}"
    method: DELETE
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    status_code: 202
    timeout: 3
  register: _gitlab_response
  retries: 3
  delay: 5
  until: _gitlab_response.status == 202
  changed_when: _gitlab_response.status == 202
  when: action == "project_delete"