---

- name: Assert task variables are defined
  ansible.builtin.assert:
      that:
          - project_name is defined

- name: Include projects list tasks
  ansible.builtin.include_tasks: projects_list.yml

- name: Lookup existing Gitlab project
  ansible.builtin.set_fact:
      projects_found_by_name: "{{ gitlab_projects_list | selectattr('name', 'equalto', project_name) | list }}"

- name: Fail if zero or more than one project found
  ansible.builtin.fail:
      msg: "{{ projects_found_by_name | length }} projects found with name {{ project_name }}"
  when:
      - projects_found_by_name | length != 1

- name: Extract project id
  ansible.builtin.set_fact:
      project_id: "{{ projects_found_by_name[0].id }}"

- name: Delete Gitlab project
  ansible.builtin.uri:
      url: "{{ gitlab_projects_url }}/{{ project_id }}"
      method: DELETE
      headers:
          PRIVATE-TOKEN: "{{ gitlab_api_token }}"
      status_code: 202
      timeout: 3
  register: _gitlab_response
  retries: 3
  delay: 5
  until: _gitlab_response.status == 202
  changed_when: _gitlab_response.status == 202
